- hosts: web
  tasks:
    - name: Install software on CentOS 7
      ignore_errors: yes
      become: true
      yum: pkg={{ item }} state=present
      with_items:
        - yum-plugin-fastestmirror
        - rsync
        - epel-release
        - mariadb-server
        - mariadb
        - lighttpd
        - lighttpd-fastcgi
        - php-cli
        - mono-web.x86_64
        - openvpn.x86_64
        - ntp
        - php-mysql
        - vim 
        - net-snmp
        - dmidecode
        - socat
        - nmap
        - dialog
        - xinetd
        - sysstat
        - openssl-devel
        - net-snmp-utils
        - gcc
        - make
        - postfix
        - mc
        - bc
        - net-tools 
        - wget
        - traceroute
        - htop
